apiVersion: skaffold/v3
kind: Config
build:
  local:
    push: false
  artifacts:
    - image: abhi02tr/auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - dest: .
            src: "src/**/.ts"
manifests:
  rawYaml:
    - ./infra/k8s/*
deploy:
  kubectl: {}
