apiVersion: skaffold/v3
kind: Config
build:
  local:
    push: false
    tryImportMissing: true
  artifacts:
    - image: abhi02tr/auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - dest: .
            src: "src/**/*.ts"
    - image: abhi02tr/client
      context: client
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - dest: .
            src: "**/*.ts"
          - src: "**/*.tsx"
            dest: .
manifests:
  rawYaml:
    - ./infra/k8s/*
deploy:
  kubectl: {}
