import type { Metadata } from "next";
import { Inter } from "next/font/google";
import axios from "axios";
import { cookies } from "next/headers";

import Header from "./components/header";

import "bootstrap/dist/css/bootstrap.min.css";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Ticketing App",
  description: "Generated by create next app",
};

async function getData() {
  const cookieStore = cookies();
  const session = cookieStore.get("session");

  try {
    if (typeof window === "undefined") {
      const { data } = await axios.get(
        "http://ingress-nginx-controller.ingress-nginx.svc.cluster.local/api/v1/users/currentuser",
        {
          headers: {
            Host: "ticketing.dev",
            Cookie: `${session?.name}=${session?.value}`,
          },
        }
      );
      return data;
    } else {
      const response = await axios.get("/api/v1/users/currentuser");
      if (response.status !== 200) {
        throw new Error("some probelm");
      }
      return response.data;
    }
    // return {};
  } catch (err: any) {
    // console.log(err);
  }
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const data = await getData();

  return (
    <html lang="en">
      <body className={inter.className}>
        {data ? (
          <Header id={data.currentUser.id} email={data.currentUser.email} />
        ) : (
          <Header id={undefined} email={undefined} />
        )}
        <div className="container">{children}</div>
      </body>
    </html>
  );
}
