apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-srv
  labels:
    name: ingress-srv
spec:
  rules:
    - host: ticketing.dev
      http:
        paths:
          - pathType: Prefix
            path: "/api/v1/users/signup"
            backend:
              service:
                name: auth-srv
                port:
                  number: 3000
  ingressClassName: nginx
